// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class TItleUIViewModel : ObservableObject
{
    private float tItleUIAlpha;

    public float TItleUIAlpha
    {
        get => tItleUIAlpha;
        set => SetProperty(ref tItleUIAlpha, value);
    }
}
}
