// <auto-generated />
using System.ComponentModel;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class TItleUIView
{
    [SerializeField] private CanvasGroup tItleUIAlpha;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.TItleUIAlpha)) && tItleUIAlpha != null)
            {
                tItleUIAlpha.alpha = ViewModel.TItleUIAlpha;
            }
    }
}
}
