// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class TItleUIViewModel : ObservableObject
{
    private float tItleUIAlpha;

    public float TItleUIAlpha
    {
        get => tItleUIAlpha;
        set => SetProperty(ref tItleUIAlpha, value);
    }

    private UnityEngine.Vector3 buttonScale;

    public UnityEngine.Vector3 ButtonScale
    {
        get => buttonScale;
        set => SetProperty(ref buttonScale, value);
    }
}
}
