// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class SkinBoxView
{
    [SerializeField] private Image skinBoxMaskPatternSprite;
    [SerializeField] private TMP_Text skinBoxMaskPatternTextLabelSkinNameTxtText;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.Pattern)) && skinBoxMaskPatternSprite != null)
            {
                skinBoxMaskPatternSprite.sprite = ViewModel.Pattern;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.SkinNameTxt)) && skinBoxMaskPatternTextLabelSkinNameTxtText != null)
            {
                skinBoxMaskPatternTextLabelSkinNameTxtText.text = ViewModel.SkinNameTxt;
            }
    }
}
}
