// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class SkinBoxViewModel : ObservableObject
{
    private UnityEngine.Sprite pattern;

    public UnityEngine.Sprite Pattern
    {
        get => pattern;
        set => SetProperty(ref pattern, value);
    }

    private string skinNameTxt;

    public string SkinNameTxt
    {
        get => skinNameTxt;
        set => SetProperty(ref skinNameTxt, value);
    }
}
}
