// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class EnemyProfileUIViewModel : ObservableObject
{
    private string no;

    public string No
    {
        get => no;
        set => SetProperty(ref no, value);
    }

    private string nameTxt;

    public string NameTxt
    {
        get => nameTxt;
        set => SetProperty(ref nameTxt, value);
    }

    private float health;

    public float Health
    {
        get => health;
        set => SetProperty(ref health, value);
    }

    private float healthMinValue;

    public float HealthMinValue
    {
        get => healthMinValue;
        set => SetProperty(ref healthMinValue, value);
    }

    private float healthMaxValue;

    public float HealthMaxValue
    {
        get => healthMaxValue;
        set => SetProperty(ref healthMaxValue, value);
    }
}
}
