// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class EnemyProfileUIView
{
    private bool isApplyingViewModel;

    [SerializeField] private TMP_Text enemyProfileUICanvasNoTextText;
    [SerializeField] private TMP_Text enemyProfileUICanvasNameTextLabelNameTxtText;
    [SerializeField] private Slider enemyProfileUICanvasHealthSliderValue;
    [SerializeField] private Slider enemyProfileUICanvasHealthSliderMinValue;
    [SerializeField] private Slider enemyProfileUICanvasHealthSliderMaxValue;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

        if (enemyProfileUICanvasHealthSliderValue != null)
        {
            enemyProfileUICanvasHealthSliderValue.onValueChanged.AddListener(OnEnemyProfileUICanvasHealthSliderValueChanged);
        }
    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

        if (enemyProfileUICanvasHealthSliderValue != null)
        {
            enemyProfileUICanvasHealthSliderValue.onValueChanged.RemoveListener(OnEnemyProfileUICanvasHealthSliderValueChanged);
        }
    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }

        isApplyingViewModel = true;
        try
        {

            if ((propertyName == null || propertyName == nameof(ViewModel.No)) && enemyProfileUICanvasNoTextText != null)
            {
                enemyProfileUICanvasNoTextText.text = ViewModel.No;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.NameTxt)) && enemyProfileUICanvasNameTextLabelNameTxtText != null)
            {
                enemyProfileUICanvasNameTextLabelNameTxtText.text = ViewModel.NameTxt;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.Health)) && enemyProfileUICanvasHealthSliderValue != null)
            {
                enemyProfileUICanvasHealthSliderValue.value = ViewModel.Health;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.HealthMinValue)) && enemyProfileUICanvasHealthSliderMinValue != null)
            {
                enemyProfileUICanvasHealthSliderMinValue.minValue = ViewModel.HealthMinValue;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.HealthMaxValue)) && enemyProfileUICanvasHealthSliderMaxValue != null)
            {
                enemyProfileUICanvasHealthSliderMaxValue.maxValue = ViewModel.HealthMaxValue;
            }
        }
        finally
        {
            isApplyingViewModel = false;
        }
    }

    private void OnEnemyProfileUICanvasHealthSliderValueChanged(float value)
    {
        if (isApplyingViewModel || ViewModel == null)
        {
            return;
        }

        ViewModel.Health = value;
    }
}
}
