// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class GameOverUIViewModel : ObservableObject
{
    private string stageTxt;

    public string StageTxt
    {
        get => stageTxt;
        set => SetProperty(ref stageTxt, value);
    }
}
}
