// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class ComboUIViewModel : ObservableObject
{
    private UnityEngine.Vector2 comboPosition;

    public UnityEngine.Vector2 ComboPosition
    {
        get => comboPosition;
        set => SetProperty(ref comboPosition, value);
    }

    private UnityEngine.Vector3 comboScale;

    public UnityEngine.Vector3 ComboScale
    {
        get => comboScale;
        set => SetProperty(ref comboScale, value);
    }

    private float comboAlpha;

    public float ComboAlpha
    {
        get => comboAlpha;
        set => SetProperty(ref comboAlpha, value);
    }

    private string textTMP1;

    public string TextTMP1
    {
        get => textTMP1;
        set => SetProperty(ref textTMP1, value);
    }
}
}
