// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class ComboUIView
{
    [SerializeField] private RectTransform comboUIComboAnchoredPosition;
    [SerializeField] private RectTransform comboUIComboLocalScale;
    [SerializeField] private CanvasGroup comboUIComboAlpha;
    [SerializeField] private TMP_Text comboUIComboGameObjectTextTMP1Text;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.ComboPosition)) && comboUIComboAnchoredPosition != null)
            {
                comboUIComboAnchoredPosition.anchoredPosition = ViewModel.ComboPosition;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.ComboScale)) && comboUIComboLocalScale != null)
            {
                comboUIComboLocalScale.localScale = ViewModel.ComboScale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.ComboAlpha)) && comboUIComboAlpha != null)
            {
                comboUIComboAlpha.alpha = ViewModel.ComboAlpha;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMP1)) && comboUIComboGameObjectTextTMP1Text != null)
            {
                comboUIComboGameObjectTextTMP1Text.text = ViewModel.TextTMP1;
            }
    }
}
}
