// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class ScoreUIView
{
    [SerializeField] private TMP_Text scoreUICurrentScoreTxtText;
    [SerializeField] private RectTransform scoreUICurrentScoreTxtLocalScale;
    [SerializeField] private TMP_Text scoreUIBestScoreTxtText;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.CurrentStageTxt)) && scoreUICurrentScoreTxtText != null)
            {
                scoreUICurrentScoreTxtText.text = ViewModel.CurrentStageTxt;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.CurrentStageScale)) && scoreUICurrentScoreTxtLocalScale != null)
            {
                scoreUICurrentScoreTxtLocalScale.localScale = ViewModel.CurrentStageScale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BestStageTxt)) && scoreUIBestScoreTxtText != null)
            {
                scoreUIBestScoreTxtText.text = ViewModel.BestStageTxt;
            }
    }
}
}
