// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class ScoreUIViewModel : ObservableObject
{
    private string currentStageTxt = "0";

    public string CurrentStageTxt
    {
        get => currentStageTxt;
        set => SetProperty(ref currentStageTxt, value);
    }

    private string bestStageTxt = "0";

    public string BestStageTxt
    {
        get => bestStageTxt;
        set => SetProperty(ref bestStageTxt, value);
    }
}
}
