// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class AllClearUIView
{
    [SerializeField] private RectTransform allClearUITextTMPLocalScale;
    [SerializeField] private TMP_Text allClearUITextTMPColorA;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPScale)) && allClearUITextTMPLocalScale != null)
            {
                allClearUITextTMPLocalScale.localScale = ViewModel.TextTMPScale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPAlpha)) && allClearUITextTMPColorA != null)
            {
                var color = allClearUITextTMPColorA.color;
                color.a = ViewModel.TextTMPAlpha;
                allClearUITextTMPColorA.color = color;
            }
    }
}
}
