// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class AllClearUIView
{
    [SerializeField] private RectTransform allClearUIAnchoredPosition;
    [SerializeField] private RectTransform allClearUIAnchoredPositionX;
    [SerializeField] private RectTransform allClearUIAnchoredPositionY;
    [SerializeField] private RectTransform allClearUISizeDelta;
    [SerializeField] private RectTransform allClearUISizeDeltaX;
    [SerializeField] private RectTransform allClearUISizeDeltaY;
    [SerializeField] private RectTransform allClearUILocalEulerAnglesZ;
    [SerializeField] private RectTransform allClearUILocalScale;
    [SerializeField] private RectTransform allClearUILocalScaleX;
    [SerializeField] private RectTransform allClearUILocalScaleY;
    [SerializeField] private RectTransform allClearUITextTMPAnchoredPosition;
    [SerializeField] private RectTransform allClearUITextTMPAnchoredPositionX;
    [SerializeField] private RectTransform allClearUITextTMPAnchoredPositionY;
    [SerializeField] private RectTransform allClearUITextTMPSizeDelta;
    [SerializeField] private RectTransform allClearUITextTMPSizeDeltaX;
    [SerializeField] private RectTransform allClearUITextTMPSizeDeltaY;
    [SerializeField] private RectTransform allClearUITextTMPLocalEulerAnglesZ;
    [SerializeField] private RectTransform allClearUITextTMPLocalScale;
    [SerializeField] private RectTransform allClearUITextTMPLocalScaleX;
    [SerializeField] private RectTransform allClearUITextTMPLocalScaleY;
    [SerializeField] private TMP_Text allClearUITextTMPText;
    [SerializeField] private TMP_Text allClearUITextTMPColor;
    [SerializeField] private TMP_Text allClearUITextTMPColorA;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIPosition)) && allClearUIAnchoredPosition != null)
            {
                allClearUIAnchoredPosition.anchoredPosition = ViewModel.AllClearUIPosition;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIX)) && allClearUIAnchoredPositionX != null)
            {
                var position = allClearUIAnchoredPositionX.anchoredPosition;
                position.x = ViewModel.AllClearUIX;
                allClearUIAnchoredPositionX.anchoredPosition = position;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIY)) && allClearUIAnchoredPositionY != null)
            {
                var position = allClearUIAnchoredPositionY.anchoredPosition;
                position.y = ViewModel.AllClearUIY;
                allClearUIAnchoredPositionY.anchoredPosition = position;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUISize)) && allClearUISizeDelta != null)
            {
                allClearUISizeDelta.sizeDelta = ViewModel.AllClearUISize;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIWidth)) && allClearUISizeDeltaX != null)
            {
                var size = allClearUISizeDeltaX.sizeDelta;
                size.x = ViewModel.AllClearUIWidth;
                allClearUISizeDeltaX.sizeDelta = size;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIHeight)) && allClearUISizeDeltaY != null)
            {
                var size = allClearUISizeDeltaY.sizeDelta;
                size.y = ViewModel.AllClearUIHeight;
                allClearUISizeDeltaY.sizeDelta = size;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIRotationZ)) && allClearUILocalEulerAnglesZ != null)
            {
                var eulerAngles = allClearUILocalEulerAnglesZ.localEulerAngles;
                eulerAngles.z = ViewModel.AllClearUIRotationZ;
                allClearUILocalEulerAnglesZ.localEulerAngles = eulerAngles;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIScale)) && allClearUILocalScale != null)
            {
                allClearUILocalScale.localScale = ViewModel.AllClearUIScale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIScaleX)) && allClearUILocalScaleX != null)
            {
                var scale = allClearUILocalScaleX.localScale;
                scale.x = ViewModel.AllClearUIScaleX;
                allClearUILocalScaleX.localScale = scale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.AllClearUIScaleY)) && allClearUILocalScaleY != null)
            {
                var scale = allClearUILocalScaleY.localScale;
                scale.y = ViewModel.AllClearUIScaleY;
                allClearUILocalScaleY.localScale = scale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPPosition)) && allClearUITextTMPAnchoredPosition != null)
            {
                allClearUITextTMPAnchoredPosition.anchoredPosition = ViewModel.TextTMPPosition;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPX)) && allClearUITextTMPAnchoredPositionX != null)
            {
                var position = allClearUITextTMPAnchoredPositionX.anchoredPosition;
                position.x = ViewModel.TextTMPX;
                allClearUITextTMPAnchoredPositionX.anchoredPosition = position;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPY)) && allClearUITextTMPAnchoredPositionY != null)
            {
                var position = allClearUITextTMPAnchoredPositionY.anchoredPosition;
                position.y = ViewModel.TextTMPY;
                allClearUITextTMPAnchoredPositionY.anchoredPosition = position;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPSize)) && allClearUITextTMPSizeDelta != null)
            {
                allClearUITextTMPSizeDelta.sizeDelta = ViewModel.TextTMPSize;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPWidth)) && allClearUITextTMPSizeDeltaX != null)
            {
                var size = allClearUITextTMPSizeDeltaX.sizeDelta;
                size.x = ViewModel.TextTMPWidth;
                allClearUITextTMPSizeDeltaX.sizeDelta = size;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPHeight)) && allClearUITextTMPSizeDeltaY != null)
            {
                var size = allClearUITextTMPSizeDeltaY.sizeDelta;
                size.y = ViewModel.TextTMPHeight;
                allClearUITextTMPSizeDeltaY.sizeDelta = size;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPRotationZ)) && allClearUITextTMPLocalEulerAnglesZ != null)
            {
                var eulerAngles = allClearUITextTMPLocalEulerAnglesZ.localEulerAngles;
                eulerAngles.z = ViewModel.TextTMPRotationZ;
                allClearUITextTMPLocalEulerAnglesZ.localEulerAngles = eulerAngles;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPScale)) && allClearUITextTMPLocalScale != null)
            {
                allClearUITextTMPLocalScale.localScale = ViewModel.TextTMPScale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPScaleX)) && allClearUITextTMPLocalScaleX != null)
            {
                var scale = allClearUITextTMPLocalScaleX.localScale;
                scale.x = ViewModel.TextTMPScaleX;
                allClearUITextTMPLocalScaleX.localScale = scale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPScaleY)) && allClearUITextTMPLocalScaleY != null)
            {
                var scale = allClearUITextTMPLocalScaleY.localScale;
                scale.y = ViewModel.TextTMPScaleY;
                allClearUITextTMPLocalScaleY.localScale = scale;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMP)) && allClearUITextTMPText != null)
            {
                allClearUITextTMPText.text = ViewModel.TextTMP;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPColor)) && allClearUITextTMPColor != null)
            {
                allClearUITextTMPColor.color = ViewModel.TextTMPColor;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.TextTMPAlpha)) && allClearUITextTMPColorA != null)
            {
                var color = allClearUITextTMPColorA.color;
                color.a = ViewModel.TextTMPAlpha;
                allClearUITextTMPColorA.color = color;
            }
    }
}
}
