// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class AllClearUIViewModel : ObservableObject
{
    private UnityEngine.Vector2 allClearUIPosition;

    public UnityEngine.Vector2 AllClearUIPosition
    {
        get => allClearUIPosition;
        set => SetProperty(ref allClearUIPosition, value);
    }

    private float allClearUIX;

    public float AllClearUIX
    {
        get => allClearUIX;
        set => SetProperty(ref allClearUIX, value);
    }

    private float allClearUIY;

    public float AllClearUIY
    {
        get => allClearUIY;
        set => SetProperty(ref allClearUIY, value);
    }

    private UnityEngine.Vector2 allClearUISize;

    public UnityEngine.Vector2 AllClearUISize
    {
        get => allClearUISize;
        set => SetProperty(ref allClearUISize, value);
    }

    private float allClearUIWidth;

    public float AllClearUIWidth
    {
        get => allClearUIWidth;
        set => SetProperty(ref allClearUIWidth, value);
    }

    private float allClearUIHeight;

    public float AllClearUIHeight
    {
        get => allClearUIHeight;
        set => SetProperty(ref allClearUIHeight, value);
    }

    private float allClearUIRotationZ;

    public float AllClearUIRotationZ
    {
        get => allClearUIRotationZ;
        set => SetProperty(ref allClearUIRotationZ, value);
    }

    private UnityEngine.Vector3 allClearUIScale;

    public UnityEngine.Vector3 AllClearUIScale
    {
        get => allClearUIScale;
        set => SetProperty(ref allClearUIScale, value);
    }

    private float allClearUIScaleX;

    public float AllClearUIScaleX
    {
        get => allClearUIScaleX;
        set => SetProperty(ref allClearUIScaleX, value);
    }

    private float allClearUIScaleY;

    public float AllClearUIScaleY
    {
        get => allClearUIScaleY;
        set => SetProperty(ref allClearUIScaleY, value);
    }

    private UnityEngine.Vector2 textTMPPosition;

    public UnityEngine.Vector2 TextTMPPosition
    {
        get => textTMPPosition;
        set => SetProperty(ref textTMPPosition, value);
    }

    private float textTMPX;

    public float TextTMPX
    {
        get => textTMPX;
        set => SetProperty(ref textTMPX, value);
    }

    private float textTMPY;

    public float TextTMPY
    {
        get => textTMPY;
        set => SetProperty(ref textTMPY, value);
    }

    private UnityEngine.Vector2 textTMPSize;

    public UnityEngine.Vector2 TextTMPSize
    {
        get => textTMPSize;
        set => SetProperty(ref textTMPSize, value);
    }

    private float textTMPWidth;

    public float TextTMPWidth
    {
        get => textTMPWidth;
        set => SetProperty(ref textTMPWidth, value);
    }

    private float textTMPHeight;

    public float TextTMPHeight
    {
        get => textTMPHeight;
        set => SetProperty(ref textTMPHeight, value);
    }

    private float textTMPRotationZ;

    public float TextTMPRotationZ
    {
        get => textTMPRotationZ;
        set => SetProperty(ref textTMPRotationZ, value);
    }

    private UnityEngine.Vector3 textTMPScale;

    public UnityEngine.Vector3 TextTMPScale
    {
        get => textTMPScale;
        set => SetProperty(ref textTMPScale, value);
    }

    private float textTMPScaleX;

    public float TextTMPScaleX
    {
        get => textTMPScaleX;
        set => SetProperty(ref textTMPScaleX, value);
    }

    private float textTMPScaleY;

    public float TextTMPScaleY
    {
        get => textTMPScaleY;
        set => SetProperty(ref textTMPScaleY, value);
    }

    private string textTMP;

    public string TextTMP
    {
        get => textTMP;
        set => SetProperty(ref textTMP, value);
    }

    private UnityEngine.Color textTMPColor;

    public UnityEngine.Color TextTMPColor
    {
        get => textTMPColor;
        set => SetProperty(ref textTMPColor, value);
    }

    private float textTMPAlpha;

    public float TextTMPAlpha
    {
        get => textTMPAlpha;
        set => SetProperty(ref textTMPAlpha, value);
    }
}
}
