// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class AllClearUIViewModel : ObservableObject
{
    private UnityEngine.Vector3 textTMPScale;

    public UnityEngine.Vector3 TextTMPScale
    {
        get => textTMPScale;
        set => SetProperty(ref textTMPScale, value);
    }

    private float textTMPAlpha;

    public float TextTMPAlpha
    {
        get => textTMPAlpha;
        set => SetProperty(ref textTMPAlpha, value);
    }
}
}
