// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class GameOverUIViewModel : ObservableObject
{
    private string scoreTxt;

    public string ScoreTxt
    {
        get => scoreTxt;
        set => SetProperty(ref scoreTxt, value);
    }
}
}
