// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class BlockSlotView
{
    [SerializeField] private RectTransform blockSlot1BlockImage1LocalEulerAnglesZ;
    [SerializeField] private RawImage blockSlot1BlockImage1Texture;
    [SerializeField] private RawImage blockSlot1BlockImage1ColorA;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1RotationZ)) && blockSlot1BlockImage1LocalEulerAnglesZ != null)
            {
                var eulerAngles = blockSlot1BlockImage1LocalEulerAnglesZ.localEulerAngles;
                eulerAngles.z = ViewModel.BlockImage1RotationZ;
                blockSlot1BlockImage1LocalEulerAnglesZ.localEulerAngles = eulerAngles;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1Texture)) && blockSlot1BlockImage1Texture != null)
            {
                blockSlot1BlockImage1Texture.texture = ViewModel.BlockImage1Texture;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1Alpha)) && blockSlot1BlockImage1ColorA != null)
            {
                var color = blockSlot1BlockImage1ColorA.color;
                color.a = ViewModel.BlockImage1Alpha;
                blockSlot1BlockImage1ColorA.color = color;
            }
    }
}
}
