// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class BlockSlotViewModel : ObservableObject
{
    private UnityEngine.Sprite blockImage1;

    public UnityEngine.Sprite BlockImage1
    {
        get => blockImage1;
        set => SetProperty(ref blockImage1, value);
    }

    private UnityEngine.Color blockImage1Color;

    public UnityEngine.Color BlockImage1Color
    {
        get => blockImage1Color;
        set => SetProperty(ref blockImage1Color, value);
    }
}
}
