// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class BlockSlotView
{
    [SerializeField] private Image blockSlotBlockImage1Sprite;
    [SerializeField] private Image blockSlotBlockImage1Color;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1)) && blockSlotBlockImage1Sprite != null)
            {
                blockSlotBlockImage1Sprite.sprite = ViewModel.BlockImage1;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1Color)) && blockSlotBlockImage1Color != null)
            {
                blockSlotBlockImage1Color.color = ViewModel.BlockImage1Color;
            }
    }
}
}
