// <auto-generated />
using Mvvm;
using UnityEngine;

namespace Game.UI
{
public sealed partial class BlockSlotViewModel : ObservableObject
{
    private UnityEngine.Texture blockImage1Texture;

    public UnityEngine.Texture BlockImage1Texture
    {
        get => blockImage1Texture;
        set => SetProperty(ref blockImage1Texture, value);
    }

    private UnityEngine.Color blockImage1Color;

    public UnityEngine.Color BlockImage1Color
    {
        get => blockImage1Color;
        set => SetProperty(ref blockImage1Color, value);
    }

    private float blockImage1Alpha;

    public float BlockImage1Alpha
    {
        get => blockImage1Alpha;
        set => SetProperty(ref blockImage1Alpha, value);
    }
}
}
