using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Mvvm.Editor
{
    public static class MvvmCodeGenerator
    {
        public static void Generate(MvvmBindingProfile profile)
        {
            if (profile == null)
            {
                throw new ArgumentNullException(nameof(profile));
            }

            if (string.IsNullOrWhiteSpace(profile.viewClassName) || string.IsNullOrWhiteSpace(profile.viewModelClassName))
            {
                throw new InvalidOperationException("View class name and ViewModel class name are required.");
            }

            var outputFolder = string.IsNullOrWhiteSpace(profile.outputFolder)
                ? "Assets/mvvm/Generated"
                : profile.outputFolder;

            EnsureAssetFolder(outputFolder);

            var viewPath = Path.Combine(outputFolder, profile.viewClassName + ".Generated.cs");
            var viewUserPath = Path.Combine(outputFolder, profile.viewClassName + ".cs");
            var viewModelPath = Path.Combine(outputFolder, profile.viewModelClassName + ".cs");
            var viewModelGeneratedPath = Path.Combine(outputFolder, profile.viewModelClassName + ".Generated.cs");

            File.WriteAllText(viewPath, BuildGeneratedView(profile), Encoding.UTF8);
            File.WriteAllText(viewModelGeneratedPath, BuildGeneratedViewModel(profile, viewModelPath), Encoding.UTF8);

            if (!File.Exists(viewUserPath))
            {
                File.WriteAllText(viewUserPath, BuildUserView(profile), Encoding.UTF8);
            }

            if (!File.Exists(viewModelPath))
            {
                File.WriteAllText(viewModelPath, BuildUserViewModel(profile), Encoding.UTF8);
            }
            else
            {
                EnsurePartialClass(viewModelPath, profile.viewModelClassName);
            }

            MvvmPostGenerateWireProcessor.Schedule(profile);
            AssetDatabase.Refresh();
        }

        private static string BuildUserView(MvvmBindingProfile profile)
        {
            var ns = profile.namespaceName;
            var sb = new StringBuilder();
            sb.AppendLine("using Mvvm;");
            sb.AppendLine();
            AppendNamespaceStart(sb, ns);
            sb.AppendLine($"public sealed partial class {profile.viewClassName} : MvvmView<{profile.viewModelClassName}>");
            sb.AppendLine("{");
            sb.AppendLine("}");
            AppendNamespaceEnd(sb, ns);
            return sb.ToString();
        }

        private static string BuildUserViewModel(MvvmBindingProfile profile)
        {
            var ns = profile.namespaceName;
            var sb = new StringBuilder();
            sb.AppendLine("using Mvvm;");
            sb.AppendLine();
            AppendNamespaceStart(sb, ns);
            sb.AppendLine($"public sealed partial class {profile.viewModelClassName}");
            sb.AppendLine("{");
            sb.AppendLine("}");
            AppendNamespaceEnd(sb, ns);
            return sb.ToString();
        }

        private static string BuildGeneratedViewModel(MvvmBindingProfile profile, string userViewModelPath)
        {
            var ns = profile.namespaceName;
            var members = profile.bindings
                .Where(x => x.enabled && !string.IsNullOrWhiteSpace(x.viewModelMember))
                .GroupBy(x => x.viewModelMember)
                .Select(x => x.First())
                .ToList();
            var existingMembers = ReadExistingMemberNames(userViewModelPath);
            var userHasBaseClass = UserViewModelHasObservableBase(userViewModelPath, profile.viewModelClassName);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using Mvvm;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            AppendNamespaceStart(sb, ns);
            if (userHasBaseClass)
            {
                sb.AppendLine($"public sealed partial class {profile.viewModelClassName}");
            }
            else
            {
                sb.AppendLine($"public sealed partial class {profile.viewModelClassName} : ObservableObject");
            }
            sb.AppendLine("{");

            foreach (var binding in members.Where(x => x.mode != MvvmBindingMode.Command && !existingMembers.Contains(x.viewModelMember)))
            {
                var type = ToCSharpType(binding.valueType);
                var field = MvvmBindingScanner.ToCamelCase("_" + binding.viewModelMember);
                sb.AppendLine($"    private {type} {field};");
                sb.AppendLine();
                sb.AppendLine($"    public {type} {binding.viewModelMember}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {field};");
                sb.AppendLine($"        set => SetProperty(ref {field}, value);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            var commands = members.Where(x => x.mode == MvvmBindingMode.Command && !existingMembers.Contains(x.viewModelMember)).ToList();
            foreach (var command in commands)
            {
                var field = MvvmBindingScanner.ToCamelCase("_" + command.viewModelMember);
                var methodName = command.viewModelMember.EndsWith("Command")
                    ? command.viewModelMember.Substring(0, command.viewModelMember.Length - "Command".Length)
                    : command.viewModelMember;
                methodName = "Execute" + MvvmBindingScanner.ToPascalCase(methodName);
                sb.AppendLine($"    private RelayCommand {field};");
                sb.AppendLine();
                sb.AppendLine($"    public RelayCommand {command.viewModelMember} => {field} ?? ({field} = new RelayCommand({methodName}));");
                sb.AppendLine();
                sb.AppendLine($"    partial void On{MvvmBindingScanner.ToPascalCase(methodName)}();");
                sb.AppendLine();
                sb.AppendLine($"    private void {methodName}()");
                sb.AppendLine("    {");
                sb.AppendLine($"        On{MvvmBindingScanner.ToPascalCase(methodName)}();");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            TrimTrailingBlankLine(sb);
            sb.AppendLine("}");
            AppendNamespaceEnd(sb, ns);
            return sb.ToString();
        }

        private static string BuildGeneratedView(MvvmBindingProfile profile)
        {
            var ns = profile.namespaceName;
            var bindings = profile.bindings.Where(x => x.enabled).ToList();
            var hasTwoWayBinding = bindings.Any(x => x.mode == MvvmBindingMode.TwoWay);
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using TMPro;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();
            AppendNamespaceStart(sb, ns);
            sb.AppendLine($"public sealed partial class {profile.viewClassName}");
            sb.AppendLine("{");
            if (hasTwoWayBinding)
            {
                sb.AppendLine("    private bool isApplyingViewModel;");
                sb.AppendLine();
            }

            foreach (var binding in bindings)
            {
                sb.AppendLine($"    [SerializeField] private {ToComponentAlias(binding.componentType)} {binding.fieldName};");
            }

            sb.AppendLine();
            sb.AppendLine("    protected override void OnBind()");
            sb.AppendLine("    {");
            sb.AppendLine("        ApplyViewModelToView();");
            sb.AppendLine("        if (ViewModel is INotifyPropertyChanged observable)");
            sb.AppendLine("        {");
            sb.AppendLine("            observable.PropertyChanged += OnViewModelPropertyChanged;");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var binding in bindings)
            {
                AppendAddListener(sb, binding);
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    protected override void OnUnbind()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (ViewModel is INotifyPropertyChanged observable)");
            sb.AppendLine("        {");
            sb.AppendLine("            observable.PropertyChanged -= OnViewModelPropertyChanged;");
            sb.AppendLine("        }");
            sb.AppendLine();

            foreach (var binding in bindings)
            {
                AppendRemoveListener(sb, binding);
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)");
            sb.AppendLine("    {");
            sb.AppendLine("        ApplyViewModelToView(e.PropertyName);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private void ApplyViewModelToView(string propertyName = null)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (ViewModel == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
            sb.AppendLine();
            if (hasTwoWayBinding)
            {
                sb.AppendLine("        isApplyingViewModel = true;");
                sb.AppendLine("        try");
                sb.AppendLine("        {");
            }

            foreach (var binding in bindings.Where(x => x.mode != MvvmBindingMode.Command))
            {
                AppendApplyBinding(sb, binding);
            }

            if (hasTwoWayBinding)
            {
                sb.AppendLine("        }");
                sb.AppendLine("        finally");
                sb.AppendLine("        {");
                sb.AppendLine("            isApplyingViewModel = false;");
                sb.AppendLine("        }");
            }
            sb.AppendLine("    }");

            foreach (var binding in bindings)
            {
                AppendHandler(sb, binding);
            }

            sb.AppendLine("}");
            AppendNamespaceEnd(sb, ns);
            return sb.ToString();
        }

        private static void AppendApplyBinding(StringBuilder sb, MvvmBindingEntry binding)
        {
            sb.AppendLine();
            sb.AppendLine($"            if ((propertyName == null || propertyName == nameof(ViewModel.{binding.viewModelMember})) && {binding.fieldName} != null)");
            sb.AppendLine("            {");
            if (binding.targetProperty == "color.a")
            {
                sb.AppendLine($"                var color = {binding.fieldName}.color;");
                sb.AppendLine($"                color.a = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.color = color;");
            }
            else if (binding.targetProperty == "anchoredPosition.x")
            {
                sb.AppendLine($"                var position = {binding.fieldName}.anchoredPosition;");
                sb.AppendLine($"                position.x = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.anchoredPosition = position;");
            }
            else if (binding.targetProperty == "anchoredPosition.y")
            {
                sb.AppendLine($"                var position = {binding.fieldName}.anchoredPosition;");
                sb.AppendLine($"                position.y = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.anchoredPosition = position;");
            }
            else if (binding.targetProperty == "sizeDelta.x")
            {
                sb.AppendLine($"                var size = {binding.fieldName}.sizeDelta;");
                sb.AppendLine($"                size.x = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.sizeDelta = size;");
            }
            else if (binding.targetProperty == "sizeDelta.y")
            {
                sb.AppendLine($"                var size = {binding.fieldName}.sizeDelta;");
                sb.AppendLine($"                size.y = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.sizeDelta = size;");
            }
            else if (binding.targetProperty == "localEulerAngles.z")
            {
                sb.AppendLine($"                var eulerAngles = {binding.fieldName}.localEulerAngles;");
                sb.AppendLine($"                eulerAngles.z = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.localEulerAngles = eulerAngles;");
            }
            else if (binding.targetProperty == "localScale.x")
            {
                sb.AppendLine($"                var scale = {binding.fieldName}.localScale;");
                sb.AppendLine($"                scale.x = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.localScale = scale;");
            }
            else if (binding.targetProperty == "localScale.y")
            {
                sb.AppendLine($"                var scale = {binding.fieldName}.localScale;");
                sb.AppendLine($"                scale.y = ViewModel.{binding.viewModelMember};");
                sb.AppendLine($"                {binding.fieldName}.localScale = scale;");
            }
            else
            {
                sb.AppendLine($"                {binding.fieldName}.{binding.targetProperty} = ViewModel.{binding.viewModelMember};");
            }
            sb.AppendLine("            }");
        }

        private static void AppendAddListener(StringBuilder sb, MvvmBindingEntry binding)
        {
            var handler = GetHandlerName(binding);
            if (binding.mode == MvvmBindingMode.Command && binding.targetProperty == "onClick")
            {
                sb.AppendLine($"        if ({binding.fieldName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {binding.fieldName}.onClick.AddListener({handler});");
                sb.AppendLine("        }");
            }
            else if (binding.mode == MvvmBindingMode.TwoWay)
            {
                var evt = GetValueChangedEvent(binding);
                sb.AppendLine($"        if ({binding.fieldName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {binding.fieldName}.{evt}.AddListener({handler});");
                sb.AppendLine("        }");
            }
        }

        private static void AppendRemoveListener(StringBuilder sb, MvvmBindingEntry binding)
        {
            var handler = GetHandlerName(binding);
            if (binding.mode == MvvmBindingMode.Command && binding.targetProperty == "onClick")
            {
                sb.AppendLine($"        if ({binding.fieldName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {binding.fieldName}.onClick.RemoveListener({handler});");
                sb.AppendLine("        }");
            }
            else if (binding.mode == MvvmBindingMode.TwoWay)
            {
                var evt = GetValueChangedEvent(binding);
                sb.AppendLine($"        if ({binding.fieldName} != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {binding.fieldName}.{evt}.RemoveListener({handler});");
                sb.AppendLine("        }");
            }
        }

        private static void AppendHandler(StringBuilder sb, MvvmBindingEntry binding)
        {
            var handler = GetHandlerName(binding);
            if (binding.mode == MvvmBindingMode.Command)
            {
                sb.AppendLine();
                sb.AppendLine($"    private void {handler}()");
                sb.AppendLine("    {");
                sb.AppendLine($"        ViewModel?.{binding.viewModelMember}?.Execute();");
                sb.AppendLine("    }");
            }
            else if (binding.mode == MvvmBindingMode.TwoWay)
            {
                sb.AppendLine();
                sb.AppendLine($"    private void {handler}({ToCSharpType(binding.valueType)} value)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (isApplyingViewModel || ViewModel == null)");
                sb.AppendLine("        {");
                sb.AppendLine("            return;");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        ViewModel.{binding.viewModelMember} = value;");
                sb.AppendLine("    }");
            }
        }

        private static string GetValueChangedEvent(MvvmBindingEntry binding)
        {
            return "onValueChanged";
        }

        private static string GetHandlerName(MvvmBindingEntry binding)
        {
            return "On" + MvvmBindingScanner.ToPascalCase(binding.fieldName) + "Changed";
        }

        private static string ToComponentAlias(string componentType)
        {
            switch (componentType)
            {
                case "TMPro.TMP_Text":
                case "TMPro.TextMeshProUGUI":
                case "TMPro.TextMeshPro":
                    return "TMP_Text";
                case "TMPro.TMP_InputField":
                    return "TMP_InputField";
                case "UnityEngine.UI.Text":
                    return "Text";
                case "UnityEngine.UI.Button":
                    return "Button";
                case "UnityEngine.UI.Slider":
                    return "Slider";
                case "UnityEngine.UI.Toggle":
                    return "Toggle";
                case "UnityEngine.UI.InputField":
                    return "InputField";
                case "UnityEngine.UI.Image":
                    return "Image";
                case "UnityEngine.UI.RawImage":
                    return "RawImage";
                case "UnityEngine.CanvasGroup":
                    return "CanvasGroup";
                case "UnityEngine.RectTransform":
                    return "RectTransform";
                default:
                    return componentType;
            }
        }

        private static HashSet<string> ReadExistingMemberNames(string path)
        {
            var names = new HashSet<string>();
            if (!File.Exists(path))
            {
                return names;
            }

            var text = File.ReadAllText(path);
            foreach (Match match in Regex.Matches(text, @"\b(?:public|internal|protected|private)\s+(?:static\s+)?[\w\.<>,]+\s+(\w+)\s*(?:\{|=>|;)"))
            {
                names.Add(match.Groups[1].Value);
            }

            return names;
        }

        private static void EnsureAssetFolder(string folder)
        {
            folder = folder.Replace("\\", "/").TrimEnd('/');
            if (AssetDatabase.IsValidFolder(folder))
            {
                return;
            }

            var parts = folder.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }

                current = next;
            }
        }

        private static bool UserViewModelHasObservableBase(string path, string className)
        {
            if (!File.Exists(path))
            {
                return false;
            }

            var text = File.ReadAllText(path);
            return Regex.IsMatch(text, $@"\bclass\s+{Regex.Escape(className)}\s*:\s*ObservableObject\b");
        }

        private static void EnsurePartialClass(string path, string className)
        {
            var text = File.ReadAllText(path);
            if (Regex.IsMatch(text, $@"\bpartial\s+class\s+{Regex.Escape(className)}\b"))
            {
                return;
            }

            var classRegex = new Regex($@"\b(public|internal)\s+(sealed\s+)?class\s+{Regex.Escape(className)}\b");
            var match = classRegex.Match(text);
            if (!match.Success)
            {
                return;
            }

            var replacement = $"{match.Groups[1].Value} {match.Groups[2].Value}partial class {className}";
            var updated = text.Remove(match.Index, match.Length).Insert(match.Index, replacement);

            if (updated != text)
            {
                File.WriteAllText(path, updated, Encoding.UTF8);
            }
        }

        private static string ToCSharpType(string type)
        {
            switch (type)
            {
                case "System.String":
                case "string":
                    return "string";
                case "System.Single":
                case "float":
                    return "float";
                case "System.Boolean":
                case "bool":
                    return "bool";
                default:
                    return type;
            }
        }

        private static void AppendNamespaceStart(StringBuilder sb, string ns)
        {
            if (!string.IsNullOrWhiteSpace(ns))
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }
        }

        private static void AppendNamespaceEnd(StringBuilder sb, string ns)
        {
            if (!string.IsNullOrWhiteSpace(ns))
            {
                sb.AppendLine("}");
            }
        }

        private static void TrimTrailingBlankLine(StringBuilder sb)
        {
            while (sb.Length >= Environment.NewLine.Length && sb.ToString().EndsWith(Environment.NewLine + Environment.NewLine))
            {
                sb.Length -= Environment.NewLine.Length;
            }
        }
    }
}
