// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class SkinSetUIView
{

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }

    }
}
}
