// <auto-generated />
using System.ComponentModel;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

namespace Game.UI
{
public sealed partial class BlockSlotsUIView
{
    [SerializeField] private Image blockSlotsUIBlockSlotsSlot1BlockImage1Sprite;
    [SerializeField] private Image blockSlotsUIBlockSlotsSlot2BlockImage2Sprite;
    [SerializeField] private Image blockSlotsUIBlockSlotsSlot3BlockImage3Sprite;

    protected override void OnBind()
    {
        ApplyViewModelToView();
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged += OnViewModelPropertyChanged;
        }

    }

    protected override void OnUnbind()
    {
        if (ViewModel is INotifyPropertyChanged observable)
        {
            observable.PropertyChanged -= OnViewModelPropertyChanged;
        }

    }

    private void OnViewModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        ApplyViewModelToView(e.PropertyName);
    }

    private void ApplyViewModelToView(string propertyName = null)
    {
        if (ViewModel == null)
        {
            return;
        }


            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage1)) && blockSlotsUIBlockSlotsSlot1BlockImage1Sprite != null)
            {
                blockSlotsUIBlockSlotsSlot1BlockImage1Sprite.sprite = ViewModel.BlockImage1;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage2)) && blockSlotsUIBlockSlotsSlot2BlockImage2Sprite != null)
            {
                blockSlotsUIBlockSlotsSlot2BlockImage2Sprite.sprite = ViewModel.BlockImage2;
            }

            if ((propertyName == null || propertyName == nameof(ViewModel.BlockImage3)) && blockSlotsUIBlockSlotsSlot3BlockImage3Sprite != null)
            {
                blockSlotsUIBlockSlotsSlot3BlockImage3Sprite.sprite = ViewModel.BlockImage3;
            }
    }
}
}
